apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  url: postgresql://postgres:pgadmin@postgres:5432/chitti_ndt
  password: pgadmin

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  key: chitti-secret-key-2024-enterprise-production

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
stringData:
  access-key: your-aws-access-key
  secret-key: your-aws-secret-key

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  REDIS_URL: redis://redis:6379
  RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
  S3_BUCKET: chitti-ndt-storage
  AWS_REGION: us-east-1
